# travis-ci.org - continuous testing environment - http://docs.travis-ci.com/
language: cpp
compiler:
  - gcc

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_script:
    - eval "${MATRIX_EVAL}"
    - echo $CC
    - pwd
    - ls -l /usr/bin/gcc
    - gcc --version
#    - sudo ln -s /usr/bin/gcc-7 /usr/bin/gcc -f
#    - sudo ln -s /usr/bin/g++-7 /usr/bin/g++ -f
#    - gcc --version

# The build machines are centos7.3 x86-64

script:
    - ./build.sh