language: cpp
compiler:
- gcc
services:
- docker

before_install:
- openssl aes-256-cbc -K $encrypted_5dbe78cb2974_key -iv $encrypted_5dbe78cb2974_iv
  -in id_rsa_aws.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 13.230.9.180\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

install:
# compile ratel by ubuntu-dev
- docker pull xujintao/docker4cpp:ubuntu-dev
- docker run -v /home/travis/build/xujintao/ratel:/project xujintao/docker4cpp:ubuntu-dev

# deploy ratel into ratel:ubuntu
- docker build -t xujintao/ratel:ubuntu ./

# compile ratel by centos-dev
- docker pull xujintao/docker4cpp:centos-dev
- docker run -v /home/travis/build/xujintao/ratel:/project xujintao/docker4cpp:ubuntu-dev

# deploy ratel into ratel:centos
- docker build -t xujintao/ratel:centos ./

before_script:
- gcc --version
- pwd

script:
# rm: cannot remove ‘Debug/spawnfcgi.dep’: Permission denied
#- ./build.sh
- docker ps -a

after_success:
- scp -o stricthostkeychecking=no -r build/* centos@13.230.9.180:/opt/www/ratel
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- docker push xujintao/ratel:ubuntu
- docker push xujintao/ratel:centos
