# travis-ci.org - continuous testing environment - http://docs.travis-ci.com/
language: cpp
compiler:
  - gcc

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_script:
# set CC(CXX) env
    - eval "${MATRIX_EVAL}"
    - echo $CC

# link gcc(g++) to gcc-7(g++-7)
    - ll /usr/bin | grep gcc
    - gcc --version
    - sudo ln -s /usr/bin/gcc-7 /usr/bin/gcc -f
    - sudo ln -s /usr/bin/g++-7 /usr/bin/g++ -f
    - gcc --version

# pwd
    - pwd


# The build machines are centos7.3 x86-64

script:
    - ./build.sh