#ifndef FASTCGIPP_CONFIG
#define FASTCGIPP_CONFIG

#define FASTCGIPP_VERSION "3.0beta"
#define FASTCGIPP_LINUX
#define FASTCGIPP_BUILD_TIME "2017-12-09T05:08:57Z"
#define FASTCGIPP_LOG_LEVEL 3

#endif
